### ISSUE TITLE
Chat box update

### ISSUE THREAD

**Issue by FlyHighhher** [FlyHighhher/My-first-agile-project#6]
As an administrator, I can add a chat box so that users can talk to each other in real-time.

# Acceptance criteria:

* Acceptance criteria 1: Users can be anonymous
* Acceptance criteria 2: The user username is visible when chatting
* Acceptance criteria 3: Users can use emoticons

# Tasks

- [ ] Update the view: add a chatbox (HTML and CSS)
- [ ] Capability of staying anonymous choice box update in the view
- [ ] Add emoticons usage capability.
