### ISSUE TITLE
User Story 8a: Plan the layout and structure of the dashboard

### ISSUE THREAD

**Issue by FlyHighhher** [FlyHighhher/My-first-agile-project#66]
As a data visualization specialist, I want to plan the layout and structure of the dashboard according to the client's specifications and preferences, so that the final product meets their expectations

# Acceptance criteria:

* Acceptance criteria 1: Understand Client specifications
* Acceptance criteria 2: Design the layout
* Acceptance criteria 3: Align with best practices

# Tasks

- [ ] Task 1: Find out the requirements of the dashboard
- [ ] Task 2: Design the layout based on the requirements.
- [ ] Task 3: Incorporate the best practices
